# 1. Data Cleaning - 타이타닉 데이터 다루기

## 1-1. 파이썬으로 데이터 둘러보기
- Pandas 라이브러리를 Import하고 타이타닉 데이터 업로드

In [3]:
import pandas as pd 

# read_csv 함수로 경로에 위치한 파일 불러오기
data = pd.read_csv("/Users/chankyulee/Desktop/ModuLABS/02_DataPreprocessing/titanic.csv")

# 결과 출력
data

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,S,1,1912-03-28
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,S,0,1912-04-03
...,...,...,...,...,...,...,...,...,...,...
880,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,S,0,1912-01-29
881,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,S,1,1912-03-30
882,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,C,1,1912-03-01
884,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,Q,0,1912-03-05

- .head(n) : 데이터의 앞 행 $n$개만 출력
- .tail(n) : 데이터의 뒤 행 $n$개만 출력

In [4]:
# 숫자를 안쓰면 기본값은 5개만 출력한다.
data.head()

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,S,1,1912-03-28
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,S,0,1912-04-03

In [5]:
data.tail()

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
880,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,S,0,1912-01-29
881,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,S,1,1912-03-30
882,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,C,1,1912-03-01
884,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,Q,0,1912-03-05

- .info() : 데이터의 인덱스, 컬럼, Null이 아닌 값 개수, 데이터 타입, 메모리 사용량을 볼 수 있다.
- .describe() : 데이터의 통계 요약표. 숫자형 데이터에 대해 개수, 평균, 표준편차, 최소/최대, 4분위값(25%, 50%, 75%, max)을 볼 수 있다.

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       885 non-null    int64
 1   Name         885 non-null    object
 2   Gendr        885 non-null    object
 3   Age          879 non-null    float64
 4   SibSp        885 non-null    int64
 5   Parch        885 non-null    int64
 6   Ticket       885 non-null    object
 7   Embarked     883 non-null    object
 8   Survived     885 non-null    int64
 9   ticket_date  885 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 69.3+ KB

In [7]:
data.describe()

           Pclass         Age       SibSp       Parch    Survived
count  885.000000  879.000000  885.000000  885.000000  885.000000
mean     2.311864   29.679181    0.525424    0.377401    0.377401
std      0.836069   13.559664    1.109746    0.805768    0.485011
min      1.000000    1.000000    0.000000    0.000000    0.000000
25%      2.000000   22.000000    0.000000    0.000000    0.000000
50%      3.000000   28.000000    0.000000    0.000000    0.000000
75%      3.000000   35.000000    1.000000    0.000000    1.000000
max      3.000000  145.000000    8.000000    6.000000    1.000000

- Series = 1열짜리 리스트 (인덱스 + 값)
- DataFrame = 여러 열의 표 (인덱스 + 열이름 + 값)

In [8]:
# Series
data['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
880                                Montvila, Rev. Juozas
881                         Graham, Miss. Margaret Edith
882             Johnston, Miss. Catherine Helen "Carrie"
883                                Behr, Mr. Karl Howell
884                                  Dooley, Mr. Patrick
Name: Name, Length: 885, dtype: object

- pd.DataFrame() : Series 객체를 DataFrame으로 만들 수 있다.

In [ ]:
# DataFrame
# 리스트 안에 리스트로 넣어주면 2차원 배열이 되므로 DataFrame 생성
data[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
880                              Montvila, Rev. Juozas
881                       Graham, Miss. Margaret Edith
882           Johnston, Miss. Catherine Helen "Carrie"
883                              Behr, Mr. Karl Howell
884                                Dooley, Mr. Patrick

[885 rows x 1 columns]

## 1-2. 불필요한 컬럼 삭제, 누락된 결측치 처리
- data.duplicated() -> Boolean Series 생성 (모든 열의 값이 이전 행과 완전히 동일하면 True, 아니면 False 반환)
- 이것을 data[]로 감싸 불리언 인덱싱 -> True에 해당하는 행(중복된 데이터)만 확인할 수 있다.
- data[] 안에 조건문을 넣어 필터링이 가능하다.

In [11]:
data[data.duplicated()]

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
25,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,S,0,1912-03-14
632,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,S,0,1912-03-16
714,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,C,1,1912-03-14